### ISSUE TITLE
Stopped working after upgrading HandBrakeCLI

### ISSUE THREAD

**Issue by jandreaucodes** [shannah/handbrake-watcher#12]
I just updated HandBrakeCLI to 'HandBrake 1.2.0' and handbrake-watcher now errors immediately on all files in the directory it's watching.

Example output:
`HandBrake 1.2.0 (2018122300) - Darwin x86_64 - https://handbrake.fr
12 CPUs detected
Invalid preset High Profile
Valid presets are:`

Then it spits out a list of valid presets, though I'm using the same one I always have "Fast 1080p30"

Here's what I'm running `handbrake-watcher handbrake.options.preset="Fast 1080p30`

**Comment by shannah** [comment]
I don't think you can add the handbrake.options... on the command line.  These need to be in the handbrake.properties file.

**Comment by jandreaucodes** [comment]
Weird, @shannah I've always ran it like that.

I just created `handbrake.properties` in the directory I'm watching.

Its contents are just `handbrake.options.preset="Fast 1080p30" source.extension=mkv avi`

I get the same error, like it's looking for "High Profile". What am I missing?

**Comment by shannah** [comment]
If it is still trying to find "High Profile", then it isn't picking up your handbrake.options.preset option.

The format for the handbrake.properties file would be:

~~~~
handbrake.options.preset=Fast 1080p30
source.extension=mkv avi
~~~~

Notice **no quotes**.

Passing on the command-line is also supported, but options need to be prefixed with `-D`.  And there appears to be a bug that causes `-Dhandbrake.options....` flags from having no effect unless that specific key is also included in the handbrake.properties file.  I'll fix this when I get a chance (isssue filed at https://github.com/shannah/handbrake-watcher/issues/14)

The command-line syntax would then be

~~~
handbrake-watcher -Dhandbrake.options.preset="Fast 1080p30" -Dsource.extension="mkv avi"
~~~~

** But you would also need to have an option `handbrake.options.preset=` in the handbrake.properties file.

I need to update the default preset to be compatible with 1.2.0.  I have filed that issue here
https://github.com/shannah/handbrake-watcher/issues/13

**Comment by jandreaucodes** [comment]
Amazing. I'm back in business. Thanks for the assist!
